# Generated by Django 5.1.5 on 2025-02-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_auth_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("TUTOR", "Tutor"),
                    ("STUDENT", "Student"),
                ],
                default="STUDENT",
                max_length=10,
            ),
        ),
    ]
