# Generated by Django 5.1.5 on 2025-02-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("EMPLOYEE", "Employee"),
                    ("CUSTOMER", "Customer"),
                ],
                default="CUSTOMER",
                max_length=10,
            ),
        ),
    ]
