# Generated by Django 5.1.5 on 2025-06-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='customer_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
